language: python

sudo: false

cache:
    directories:
        - $HOME/.cache/pip

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6-dev"
    - "nightly" # currently points to 3.7 something
    - "pypy"
    - "pypy3"

before_script:
    - "export PYTHONPATH=$PYTHONPATH:`pwd`"
    - "uname -a"
    - "cd tests"

script:
    - py.test --verbose

notifications:
    email:
        on_success: change
        on_failure: change
