{
 "title": "EMS PERRET",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deviceName",
    "query": "SHOW TAG VALUES WITH KEY = \"deviceName\""
   }
  ]
 },
 "panels": [
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deviceName" },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Digital",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Water Leak",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "waterleak",
     "measurement": "data",
     "select": [
      [
       { "params": [ "waterleak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "vdd",
     "measurement": "data",
     "select": [
      [
       { "params": [ "vdd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch On/Off",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "LSNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "lsnr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Digital",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Water Leak",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "waterleak",
     "measurement": "data",
     "select": [
      [
       { "params": [ "waterleak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "vdd",
     "measurement": "data",
     "select": [
      [
       { "params": [ "vdd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch On/Off",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "LSNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "lsnr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Digital",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Water Leak",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "waterleak",
     "measurement": "data",
     "select": [
      [
       { "params": [ "waterleak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "vdd",
     "measurement": "data",
     "select": [
      [
       { "params": [ "vdd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch On/Off",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "LSNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "lsnr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 43 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Digital",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Water Leak",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "waterleak",
     "measurement": "data",
     "select": [
      [
       { "params": [ "waterleak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "vdd",
     "measurement": "data",
     "select": [
      [
       { "params": [ "vdd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Motion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "accMotion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch On/Off",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digital" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "LSNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "lsnr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 59 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  }
 ]
}